name: "Install tfvarenv"
description: "Installs the tfvarenv CLI for a specified version"
inputs:
  version:
    description: "The version of tfvarenv to install"
    default: "v0.1.1"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Installing tfvarenv version ${{ inputs.version }}"
        cd /tmp
        curl -sL https://github.com/marcy326/tfvarenv/releases/download/${{ inputs.version }}/tfvarenv_${{ inputs.version }}_linux_amd64.tar.gz | tar zxvf -
        sudo install tfvarenv_${{ inputs.version }}_linux_amd64/tfvarenv /usr/local/bin
        rm -rf tfvarenv_${{ inputs.version }}_linux_amd64/
      shell: bash
